language: node_js

node_js:
  - "node"
  
sudo: required
dist: trusty

install:
  - npm install

script:
  - npm test

language: node_js

node_js:
  - "10.9.0"
npm: "6.4.1"

python:
  - "2.7"
  - "3.5"
