language: node_js

node_js:
  - "node"
  
sudo: required
dist: trusty

install:
  - npm install

script:
  - npm test

language: node_js

node_js:
  - "8.10.0"
npm: "3.5.2"

python:
  - "2.7"
  - "3.5"
